# Generated by Django 5.0.3 on 2024-03-13 17:20

from django.db import migrations


from django.db import migrations, models

def add_done_field(apps, schema_editor):
    Task = apps.get_model('app', 'Task')
    Task.objects.all().update(done=False)  # Opcional: Establece todos los valores de 'done' a False
    Task.objects.all().update(done=True)   # Opcional: Establece todos los valores de 'done' a True

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_done'),  # Esta es la migración anterior que refleja la eliminación del campo 'done'
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_done_field),  # Ejecuta la función add_done_field después de agregar el campo 'done'
    ]

